In [9]:
import pandas as pd
# 数据查看
df = pd.read_csv('data/sales_data_500.csv',usecols = ['订单号','产品类别','产品名称','销售数量','单价'])
df.head(10) #显示前x行数据
df.tail(10) #显示后x行数据
df.describe() #显示数据统计信息
df.info() #显示数据信息
df.shape #显示数据维度
df.columns #显示数据列名

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   订单号     500 non-null    int64
 1   产品类别    500 non-null    object
 2   产品名称    500 non-null    object
 3   销售数量    500 non-null    int64
 4   单价      500 non-null    int64
dtypes: int64(3), object(2)
memory usage: 19.7+ KB

Index(['订单号', '产品类别', '产品名称', '销售数量', '单价'], dtype='object')

In [19]:
# 数据选择
df1 = pd.read_csv('data/sales_data_500.csv',usecols = ['订单号','产品类别','产品名称','销售数量','单价'])
df1
# 选择列
# 1.1 单列
df1['产品类别']
# 1.2 多列
df1[['产品名称','单价']]

# 选择行
# 2.1 单行 -语法: df.iloc[start:stop:step] (基于行号选择,从0开始)
df1.iloc[0:5:1]
# 2.2 多行 -语法: df.loc[start:stop:step] 包含结束位置 (只看标签选择)
df1.loc[0:5:1]

         订单号  产品类别  产品名称  销售数量    单价
0  890779946  电子产品    手机     4   499
1  200604502    图书    教材     7   199
2  550455977    图书  考试资料     9    15
3  398362082    图书   工具书     3    15
4  469319644  家居用品    枕头     7    29
5  692749116  电子产品    键盘     2  4999

In [34]:
df2 = pd.read_csv('data/sales_data_500.csv')
# 数据过滤

# 销售数量>=10 df[filter条件]
df2[df2['销售数量'] >= 10]

# 产品类别是食品或图书的订单
# df2[(df2['产品类别'] == '食品') | (df2['产品类别'] == '图书' )]
df2[df2['产品类别'].isin(['食品','图书'])]

# 单价在100 - 200间 (between:包含100和200)
df2[(df2['单价'].between(100,200))]

# 销售数量>=8且单价>=100的订单 (&:逻辑与, |:逻辑或)
df2[(df2['销售数量'] >= 8) & (df2['单价'] >= 100)]

# 产品类别为服装或食品,支付方式为支付宝或微信支付
df2[df2['产品类别'].isin (['服装','食品']) & df2['支付方式'].isin (['支付宝','微信支付'])]

           订单号 产品类别 产品名称  销售数量   单价 客户所在城市  支付方式        订单日期
30   800235246   服装  牛仔裤     9  499     深圳   支付宝  2025-12-27
41   817112652   食品   薯片    10   39     厦门   支付宝  2025-12-10
50   605399561   服装  运动鞋     2   89     长沙   支付宝  2025-10-07
51   808705238   食品   咖啡     4   39     武汉   支付宝  2025-10-13
59   561588882   食品   薯片     5    5     重庆  微信支付  2025-12-20
..         ...  ...  ...   ...  ...    ...   ...         ...
457  498380251   食品  方便面     9    9     长沙  微信支付  2025-11-12
463  145822897   食品   饼干     4   15     成都  微信支付  2025-11-03
470  900742774   食品   牛奶     6   69     武汉   支付宝  2025-11-09
475  306978174   食品   饼干    10  129     北京  微信支付  2025-10-27
496  625679392   食品  方便面     3   25     合肥  微信支付  2025-10-05

[84 rows x 8 columns]