In [8]:
import pandas as pd
df = pd.read_csv('data/sales_data_500.csv',nrows = 20)

# 1.0排序 df.sort_values(by = '销售数量',ascending = False)
# 1.1根据 销售数量 降序排序
# df.sort_values(by = '销售数量',ascending = False)
# 1.2根据 价格 升序排序
df.sort_values(by = '单价',ascending = True)
# 1.3根据 价格 升序排序,价格一样,再根据 销售数量 排序(列表的形式传递)
df.sort_values(by = ['单价','销售数量'],ascending = [True,False])

          订单号  产品类别  产品名称  销售数量    单价 客户所在城市  支付方式        订单日期
4   398362082  家居用品    枕头     7   -29     深圳   银行卡  2025-12-09
2   550455977    图书  考试资料     9   -15     成都  京东白条  2025-10-15
3   398362082    图书   工具书     3    15     郑州   银行卡  2025-10-07
12  678722458    食品    饼干     3    39     武汉  京东白条  2025-11-24
18  679153816    图书  考试资料     3    45     天津  微信支付  2025-12-01
11  803771909  家居用品    枕头    10    59     苏州  微信支付  2025-11-13
7   586845604  家居用品    枕头     2    59     长沙   银行卡  2025-12-27
10  964411347    图书    漫画     1    79     武汉   支付宝  2025-11-13
15  112327652    食品   矿泉水     9    89     西安  京东白条  2025-12-24
8   853573823  家居用品    被子     6   129     成都   银行卡  2025-12-21
19  992994062    图书    绘本     1   129     深圳   银行卡  2025-11-08
13  248532577    图书    传记     7   199     天津  微信支付  2025-12-16
6   810026086    图书    绘本     4   199    NaN   支付宝  2025-10-25
14  740389325  电子产品    手机     3   199     南京    花呗  2025-10-13
1   200604502    图书    教材    -7   199    NaN   支付宝  2025.10.08
9   596348124  电子产品   钢化膜     9   299     武汉  微信支付  2025-11-09
16  566825638  电子产品  智能手表     6   499     深圳   银行卡  2025-10-15
0   890779946  电子产品    手机     4   499     武汉  微信支付  2025-10-22
17  771410971  电子产品   充电宝     3  4999     厦门   支付宝  2025-11-27
5   692749116  电子产品    键盘     2  4999     长沙   支付宝  2025-11-27

In [31]:
df = pd.read_csv('data/sales_data_500.csv',nrows = 20)
df['销售金额'] = df['单价'] * df['销售数量']
# 3.0 分组
# 3.1 根据 产品类别 分组,统计各类别的 订单数量
df.groupby('产品类别').count()
# 3.2 根据 产品类别 分组,统计各类别的 销售数量之和
df.groupby('产品类别')['销售数量'].sum()
# 3.3 根据 产品类别 分组,统计各类别的 销售金额之和
df.groupby('产品类别')['销售金额'].sum()
# 3.4 根据 产品类别 分组,统计各类别的 最小单价
df.groupby('产品类别')['单价'].min()
# 3.5 根据 产品类别 分组,统计各类别的 最大单价
df.groupby('产品类别')['单价'].max()
# 3.6 根据 产品类别 分组,统计各类别的 平均单价
df.groupby('产品类别')['单价'].mean()
# 3.7 根据 产品类别 分组,统计各类别的 单价的平均值、最大值、最小值
df.groupby('产品类别')['单价'].agg(['mean','max','min']).round(2)
# 3.8 根据 产品类别 分组,统计各类别的 销售数量之和、销售金额之和、单价的平均值
df.groupby('产品类别').agg({'销售数量':'sum','销售金额':'sum','单价':['mean']}).round(2).to_dict()

     销售数量   销售金额       单价
      sum    sum     mean
产品类别
图书     21   1049   106.25
家居用品   25   1279    54.50
电子产品   27  33273  1915.67
食品     12    918    64.00